[package]
name = "agent-bob"
author = "Garrett Comes"
description = "An AI coding agent"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["crossterm_0_29"] }

